# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'acesso.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tela_inicial_2(object):
    def setupUi(self, tela_inicial_2):
        tela_inicial_2.setObjectName("tela_inicial_2")
        tela_inicial_2.resize(721, 571)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(tela_inicial_2.sizePolicy().hasHeightForWidth())
        tela_inicial_2.setSizePolicy(sizePolicy)
        tela_inicial_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tela_inicial = QtWidgets.QWidget(tela_inicial_2)
        self.tela_inicial.setObjectName("tela_inicial")
        self.btn_acesso = QtWidgets.QPushButton(self.tela_inicial)
        self.btn_acesso.setGeometry(QtCore.QRect(250, 490, 211, 33))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_acesso.setFont(font)
        self.btn_acesso.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_acesso.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"    border-radius:10px;\n"
"    border:1px solid white;\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 0, 0);\n"
"}")
        self.btn_acesso.setObjectName("btn_acesso")
        self.txt_tds = QtWidgets.QLabel(self.tela_inicial)
        self.txt_tds.setGeometry(QtCore.QRect(140, 20, 511, 31))
        font = QtGui.QFont()
        font.setFamily("aakar")
        font.setPointSize(20)
        self.txt_tds.setFont(font)
        self.txt_tds.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_tds.setObjectName("txt_tds")
        self.logo = QtWidgets.QLabel(self.tela_inicial)
        self.logo.setGeometry(QtCore.QRect(0, 0, 731, 571))
        self.logo.setAutoFillBackground(False)
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("imagens/logo1.jpg"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.logo.raise_()
        self.btn_acesso.raise_()
        self.txt_tds.raise_()
        tela_inicial_2.setCentralWidget(self.tela_inicial)

        self.retranslateUi(tela_inicial_2)
        QtCore.QMetaObject.connectSlotsByName(tela_inicial_2)

    def retranslateUi(self, tela_inicial_2):
        _translate = QtCore.QCoreApplication.translate
        tela_inicial_2.setWindowTitle(_translate("tela_inicial_2", "UNO"))
        self.btn_acesso.setText(_translate("tela_inicial_2", "Acessar Menu"))
        self.txt_tds.setText(_translate("tela_inicial_2", "Tec. Desenvolvimento de Sistemas 2023"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tela_inicial_2 = QtWidgets.QMainWindow()
    ui = Ui_tela_inicial_2()
    ui.setupUi(tela_inicial_2)
    tela_inicial_2.show()
    sys.exit(app.exec_())
