# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pontuacao.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_tela_atualizar(object):
    def atualizar_ranking(self):
        con = sqlite3.connect("ranking.db")
        cur = con.cursor()
        cur.execute("""
          UPDATE tabela SET pontos=? WHERE id=?
        """, (self.input_nova_pontuacao.text(), self.input_id.text()))
        con.commit()
        con.close()

    def setupUi(self, tela_adicionar):
        tela_adicionar.setObjectName("tela_adicionar")
        tela_adicionar.resize(721, 571)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(tela_adicionar.sizePolicy().hasHeightForWidth())
        tela_adicionar.setSizePolicy(sizePolicy)
        tela_adicionar.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(tela_adicionar)
        self.centralwidget.setObjectName("centralwidget")
        self.logo_inicial = QtWidgets.QLabel(self.centralwidget)
        self.logo_inicial.setGeometry(QtCore.QRect(-4, 6, 731, 561))
        self.logo_inicial.setText("")
        self.logo_inicial.setPixmap(QtGui.QPixmap("../imagens/screen.jpg"))
        self.logo_inicial.setScaledContents(True)
        self.logo_inicial.setObjectName("logo_inicial")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(190, 60, 341, 471))
        self.frame.setStyleSheet("border-radius:10px")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_back = QtWidgets.QPushButton(self.frame)
        self.btn_back.setGeometry(QtCore.QRect(10, 10, 41, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_back.setFont(font)
        self.btn_back.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_back.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    \n"
"}\n"
"")
        self.btn_back.setObjectName("btn_back")
        self.btn_salvar = QtWidgets.QPushButton(self.frame)
        self.btn_salvar.setGeometry(QtCore.QRect(110, 420, 121, 31))
        self.btn_salvar.clicked.connect(self.atualizar_ranking)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_salvar.setFont(font)
        self.btn_salvar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_salvar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 170, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    border:1px solid white\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 170, 0);\n"
"}")
        self.btn_salvar.setObjectName("btn_salvar")
        self.txt_atualizacao = QtWidgets.QLabel(self.frame)
        self.txt_atualizacao.setGeometry(QtCore.QRect(80, 200, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txt_atualizacao.setFont(font)
        self.txt_atualizacao.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_atualizacao.setObjectName("txt_atualizacao")
        self.logo = QtWidgets.QLabel(self.frame)
        self.logo.setGeometry(QtCore.QRect(50, 10, 271, 191))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../imagens/uno1.png"))
        self.logo.setObjectName("logo")
        self.input_id = QtWidgets.QLineEdit(self.frame)
        self.input_id.setGeometry(QtCore.QRect(110, 280, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_id.setFont(font)
        self.input_id.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"border:1px solid red;\n"
"border-radius: 5px\n"
"}")
        self.input_id.setMaxLength(15)
        self.input_id.setAlignment(QtCore.Qt.AlignCenter)
        self.input_id.setObjectName("input_id")
        self.txt_id = QtWidgets.QLabel(self.frame)
        self.txt_id.setGeometry(QtCore.QRect(160, 260, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_id.setFont(font)
        self.txt_id.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0,5);")
        self.txt_id.setObjectName("txt_id")
        self.input_nova_pontuacao = QtWidgets.QLineEdit(self.frame)
        self.input_nova_pontuacao.setGeometry(QtCore.QRect(110, 350, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_nova_pontuacao.setFont(font)
        self.input_nova_pontuacao.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"border:1px solid red;\n"
"border-radius: 5px\n"
"}")
        self.input_nova_pontuacao.setMaxLength(4)
        self.input_nova_pontuacao.setFrame(False)
        self.input_nova_pontuacao.setAlignment(QtCore.Qt.AlignCenter)
        self.input_nova_pontuacao.setObjectName("input_nova_pontuacao")
        self.txt_novo_pontos = QtWidgets.QLabel(self.frame)
        self.txt_novo_pontos.setGeometry(QtCore.QRect(110, 330, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_novo_pontos.setFont(font)
        self.txt_novo_pontos.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0,5);")
        self.txt_novo_pontos.setObjectName("txt_novo_pontos")
        tela_adicionar.setCentralWidget(self.centralwidget)

        self.retranslateUi(tela_adicionar)
        QtCore.QMetaObject.connectSlotsByName(tela_adicionar)

    def retranslateUi(self, tela_adicionar):
        _translate = QtCore.QCoreApplication.translate
        tela_adicionar.setWindowTitle(_translate("tela_adicionar", "uno"))
        self.btn_back.setText(_translate("tela_adicionar", "🔙"))
        self.btn_salvar.setText(_translate("tela_adicionar", "Atualizar"))
        self.txt_atualizacao.setText(_translate("tela_adicionar", "Atualizar pontuaçoẽs!"))
        self.txt_id.setText(_translate("tela_adicionar", "ID"))
        self.txt_novo_pontos.setText(_translate("tela_adicionar", "Nova Pontuação"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tela_adicionar = QtWidgets.QMainWindow()
    ui = Ui_tela_atualizar()
    ui.setupUi(tela_adicionar)
    tela_adicionar.show()
    sys.exit(app.exec_())
