# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3


class Ui_tela_adicionar(object):
    def adicionar_jogador(self):
        con = sqlite3.connect("ranking.db")
        cur = con.cursor()
        cur.execute("""
          INSERT INTO tabela (nome, pontos) VALUES(?,?)
        """, (self.input_nome.text(), int(self.input_pontos.text()))) 
        con.commit()
        con.close()

    def setupUi(self, tela_adicionar):
        tela_adicionar.setObjectName("tela_adicionar")
        tela_adicionar.resize(721, 521)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(tela_adicionar.sizePolicy().hasHeightForWidth())
        tela_adicionar.setSizePolicy(sizePolicy)
        tela_adicionar.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(tela_adicionar)
        self.centralwidget.setObjectName("centralwidget")
        self.logo_inicial = QtWidgets.QLabel(self.centralwidget)
        self.logo_inicial.setGeometry(QtCore.QRect(-14, 0, 741, 521))
        self.logo_inicial.setText("")
        self.logo_inicial.setPixmap(QtGui.QPixmap("../imagens/screen.jpg"))
        self.logo_inicial.setScaledContents(True)
        self.logo_inicial.setObjectName("logo_inicial")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(180, 40, 341, 441))
        self.frame.setStyleSheet("border-radius:10px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_fechar = QtWidgets.QPushButton(self.frame)
        self.btn_fechar.setGeometry(QtCore.QRect(10, 10, 31, 33))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_fechar.setFont(font)
        self.btn_fechar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_fechar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 0);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:10px\n"
"}\n"
"")
        self.btn_fechar.setObjectName("btn_fechar")
        self.logo = QtWidgets.QLabel(self.frame)
        self.logo.setGeometry(QtCore.QRect(50, 0, 271, 221))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../imagens/uno1.png"))
        self.logo.setObjectName("logo")
        self.btn_salvar = QtWidgets.QPushButton(self.frame)
        self.btn_salvar.setGeometry(QtCore.QRect(120, 400, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_salvar.setFont(font)
        self.btn_salvar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_salvar.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 127);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    border:1px solid white\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"    color: rgb(0, 0, 127);\n"
"}")
        self.btn_salvar.setObjectName("btn_salvar")
        self.txt_add = QtWidgets.QLabel(self.frame)
        self.txt_add.setGeometry(QtCore.QRect(60, 210, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.txt_add.setFont(font)
        self.txt_add.setStyleSheet("color: rgb(255, 255, 255);")
        self.txt_add.setObjectName("txt_add")
        self.input_nome = QtWidgets.QLineEdit(self.frame)
        self.input_nome.setGeometry(QtCore.QRect(120, 279, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_nome.setFont(font)
        self.input_nome.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"border:1px solid red;\n"
"border-radius: 5px\n"
"}")
        self.input_nome.setMaxLength(15)
        self.input_nome.setObjectName("input_nome")
        self.txt_pontos = QtWidgets.QLabel(self.frame)
        self.txt_pontos.setGeometry(QtCore.QRect(30, 330, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_pontos.setFont(font)
        self.txt_pontos.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0,5);")
        self.txt_pontos.setObjectName("txt_pontos")
        self.input_pontos = QtWidgets.QLineEdit(self.frame)
        self.input_pontos.setGeometry(QtCore.QRect(120, 330, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.input_pontos.setFont(font)
        self.input_pontos.setStyleSheet("QLineEdit{\n"
"background-color: rgb(255, 255, 255);\n"
"border:1px solid blue;\n"
"border-radius:5px\n"
"}")
        self.input_pontos.setMaxLength(4)
        self.input_pontos.setFrame(False)
        self.input_pontos.setAlignment(QtCore.Qt.AlignCenter)
        self.input_pontos.setObjectName("input_pontos")
        self.txt_nome = QtWidgets.QLabel(self.frame)
        self.txt_nome.setGeometry(QtCore.QRect(60, 280, 51, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_nome.setFont(font)
        self.txt_nome.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0,5);")
        self.txt_nome.setObjectName("txt_nome")
        tela_adicionar.setCentralWidget(self.centralwidget)

        self.retranslateUi(tela_adicionar)
        QtCore.QMetaObject.connectSlotsByName(tela_adicionar)

    def retranslateUi(self, tela_adicionar):
        _translate = QtCore.QCoreApplication.translate
        tela_adicionar.setWindowTitle(_translate("tela_adicionar", "uno"))
        self.btn_fechar.setText(_translate("tela_adicionar", "🔙"))
        self.btn_salvar.setText(_translate("tela_adicionar", "Salvar"))
        self.btn_salvar.clicked.connect(self.adicionar_jogador)
        self.txt_add.setText(_translate("tela_adicionar", "Adicione um novo jogador !"))
        self.txt_pontos.setText(_translate("tela_adicionar", "Pontuação:"))
        self.txt_nome.setText(_translate("tela_adicionar", "Nome:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tela_adicionar = QtWidgets.QMainWindow()
    ui = Ui_tela_adicionar()
    ui.setupUi(tela_adicionar)
    tela_adicionar.show()
    sys.exit(app.exec_())
