# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
import sqlite3


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(721, 576)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(255, 51, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.ranking = QtWidgets.QTreeWidget(self.centralwidget)
        self.ranking.setGeometry(QtCore.QRect(10, 280, 701, 291))
        self.ranking.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:5px;\n"
"border:1px solid black")
        self.ranking.setObjectName("ranking")
        self.ranking.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ranking.headerItem().setFont(0, font)
        self.ranking.headerItem().setTextAlignment(1, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ranking.headerItem().setFont(1, font)
        self.ranking.headerItem().setTextAlignment(2, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.ranking.headerItem().setFont(2, font)
        self.btn_atualizar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_atualizar.setGeometry(QtCore.QRect(290, 230, 161, 33))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_atualizar.setFont(font)
        self.btn_atualizar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_atualizar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 150, 0);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    border:1px solid white\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 170, 0);\n"
"    border:1px solid green\n"
"}")
        self.btn_atualizar.setObjectName("btn_atualizar")
        self.btn_adicionar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_adicionar.setGeometry(QtCore.QRect(30, 230, 151, 33))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_adicionar.setFont(font)
        self.btn_adicionar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_adicionar.setStyleSheet("QPushButton{\n"
"    background-color: rgb(0, 0, 127);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    border:1px solid white\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"    color: rgb(0, 0, 127);\n"
"    border:1px solid blue\n"
"}")
        self.btn_adicionar.setObjectName("btn_adicionar")
        self.btn_excluir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_excluir.setGeometry(QtCore.QRect(540, 230, 141, 33))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_excluir.setFont(font)
        self.btn_excluir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_excluir.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 0, 0);\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:5px;\n"
"    border:1px solid white\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"    color: rgb(255, 0, 0);\n"
"    border:1px solid red\n"
"}")
        self.btn_excluir.setObjectName("btn_excluir")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 721, 271))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../imagens/uno.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label.raise_()
        self.ranking.raise_()
        self.btn_atualizar.raise_()
        self.btn_adicionar.raise_()
        self.btn_excluir.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def atualizar_tabela(self):
        con = sqlite3.connect("ranking.db") 
        cur = con.cursor()
        cur.execute("""
          SELECT * FROM tabela ORDER BY pontos DESC
        """)
        tabela_nova = cur.fetchall() # retorna tupla 
        con.close
        for jogador in tabela_nova:
          novos_jogadores = QtWidgets.QTreeWidgetItem(self.ranking)
          novos_jogadores.setText(0, str(jogador[0]))
          novos_jogadores.setTextAlignment(0, Qt.AlignCenter)
          novos_jogadores.setText(1, str(jogador[1]))
          novos_jogadores.setTextAlignment(1, Qt.AlignCenter)
          novos_jogadores.setText(2, str(jogador[2]))
          novos_jogadores.setTextAlignment(2, Qt.AlignCenter)
          novos_jogadores.addChild(novos_jogadores)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UNO"))
        self.ranking.headerItem().setText(0, _translate("MainWindow", "ID"))
        self.ranking.headerItem().setText(1, _translate("MainWindow", "NOME"))
        self.ranking.headerItem().setText(2, _translate("MainWindow", "PONTOS"))
        self.ranking.setColumnWidth(0, 80)
        self.ranking.setColumnWidth(1, 450)
        self.ranking.setColumnWidth(2, 80)
        self.atualizar_tabela()
        self.btn_atualizar.setText(_translate("MainWindow", "Atualizar Pontuação"))
        self.btn_adicionar.setText(_translate("MainWindow", "Adicionar Jogador"))
        self.btn_excluir.setText(_translate("MainWindow", "Excluir Jogador"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
